grails-app/domain/cvista_login/Usuario.groovy
package cvista_login



class Usuario {
	long id
	String email
	String password
	boolean activo
	Byte [] picture
	String pictureName
	String pictureType

	static constraints = {
		id()
		email(email:true,validator:{
			val,instance ->
			def userClasses = Usuario.findAllByEmail(val);
			if(userClasses){
				for(Usuario userClass : userClasses){
					if(userClass.class.equals(instance.class) && instance.version == null){
						return ['default.email.error']
					}
				}
			}
			return true
		})
		password(password:true)
		activo()
		picture(nullable:true)
		pictureName(nullable:true)
		pictureType(nullable:true)
	}


	static mapping = {
		tablePerHierarchy true
		picture(length:2048*2048)
	}


	String toString(){
		id +" - "+email +" "+password
	}
}

grails-app/controllers/cvista_login/UsuarioController.groovy
package cvista_login



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UsuarioController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Usuario.list(params), model:[usuarioInstanceCount: Usuario.count()]
    }
	
	
	def login = {
		
	}
 
	def loginT = {
		if (request.method == 'POST') {
			def passwordHashed = params.password.encodeAsMD5()
			def u = Usuario.findByEmailAndPassword(params.email, passwordHashed)
			if (u) {
				if(u.class == UsuarioAdministrador.class){
					session.user = u
					session.invalidate()
					redirect(url:"/admin")
				
				}
				if(u.class == UsuarioBasico.class){
					session.user = u
					redirect(controller:'UsuarioBasico')
				}
				
				if(u.class == UsuarioEmpresario.class){
					session.user = u
					redirect(controller:'UsuarioEmpresario')
				}
				if(u.class == UsuarioPromotor.class){
					session.user = u
					redirect(controller:'UsuarioPromotor')
				}
				if(u.class == Usuario.class){
					session.user = u
					redirect(controller:'Usuario')
				}
				
			} else {
				flash.message = "User not found"
				redirect(controller:'main')
			}
		} else if (session.user) {
			// don't allow login while user is logged in
			redirect(controller:'main')
		}
	}
 
	def logout = {
		session.invalidate()
		redirect(controller:'main')
	}

    def show(Usuario usuarioInstance) {
        respond usuarioInstance
    }

    def create() {
        respond new Usuario(params)
    }

    @Transactional
    def save(Usuario usuarioInstance) {
        if (usuarioInstance == null) {
            notFound()
            return
        }

        if (usuarioInstance.hasErrors()) {
            respond usuarioInstance.errors, view:'create'
            return
        }

        usuarioInstance.save flush:true
		usuarioInstance.password = usuarioInstance.password.encodeAsMD5()
		
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'usuario.label', default: 'Usuario'), usuarioInstance.id])
                redirect usuarioInstance
            }
            '*' { respond usuarioInstance, [status: CREATED] }
        }
    }

    def edit(Usuario usuarioInstance) {
        respond usuarioInstance
    }

    @Transactional
    def update(Usuario usuarioInstance) {
        if (usuarioInstance == null) {
            notFound()
            return
        }

        if (usuarioInstance.hasErrors()) {
            respond usuarioInstance.errors, view:'edit'
            return
        }

        usuarioInstance.save flush:true
		usuarioInstance.password = usuarioInstance.password.encodeAsMD5()
		
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Usuario.label', default: 'Usuario'), usuarioInstance.id])
                redirect usuarioInstance
            }
            '*'{ respond usuarioInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Usuario usuarioInstance) {

        if (usuarioInstance == null) {
            notFound()
            return
        }

        usuarioInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Usuario.label', default: 'Usuario'), usuarioInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }
	
    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuario.label', default: 'Usuario'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/usuario/_form.gsp
<%@ page import="cvista_login.Usuario" %>



<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="usuario.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="email" required="" value="${usuarioInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="usuario.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="password" name="password" required="" value="${usuarioInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioInstance, field: 'activo', 'error')} ">
	<label for="activo">
		<g:message code="usuario.activo.label" default="Activo" />
		
	</label>
	<g:checkBox name="activo" value="${usuarioInstance?.activo}" />

</div>

grails-app/views/usuario/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-usuario" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:usuarioInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/usuario/edit.gsp
<%@ page import="cvista_login.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-usuario" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:usuarioInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${usuarioInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/usuario/index.gsp
<%@ page import="cvista_login.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-usuario" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="email" title="${message(code: 'usuario.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'usuario.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="activo" title="${message(code: 'usuario.activo.label', default: 'Activo')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioInstanceList}" status="i" var="usuarioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${usuarioInstance.id}">${fieldValue(bean: usuarioInstance, field: "email")}</g:link></td>
					
						<td>${fieldValue(bean: usuarioInstance, field: "password")}</td>
					
						<td><g:formatBoolean boolean="${usuarioInstance.activo}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${usuarioInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/usuario/login.gsp
<!DOCTYPE html>
<head>
<meta charset="UTF-8" />
<title>Ciudad Vista</title>

<!-- CSS Part Start-->
<asset:stylesheet src="stylesheet.css" />
<asset:stylesheet src="slideshow.css" media="screen" />
<asset:stylesheet src="flexslider.css" media="screen" />
<asset:stylesheet src="colorbox.css" media="screen" />
<asset:stylesheet src="carousel.css" media="screen" />
<!-- CSS Part End-->
<!-- JS Part Start-->
<asset:javascript src="jquery-1.7.1.min.js"/>
<asset:javascript src="jquery.nivo.slider.pack.js"/>
<asset:javascript src="jquery.flexslider.js"/>
<asset:javascript src="jquery.easing-1.3.min.js"/>
<asset:javascript src="jquery.jcarousel.min.js"/>
<asset:javascript src="jquery.colorbox-min.js"/>
<asset:javascript src="tabs.js"/>
<asset:javascript src="cloud_zoom.js"/>
<asset:javascript src="jquery.dcjqaccordion.js"/>
<asset:javascript src="custom.js"/>
<asset:javascript src="html5.js"/>

<!-- JS Part End-->

</head>
<body>
<div class="wrapper-box">
  <div class="main-wrapper">
  
  <g:render template="/common/top" />
  
  <div id="container">
      <!--Middle Part Start-->
      <div id="content">
        <!--Breadcrumb Part Start-->
        <div class="breadcrumb"> <a href="index-2.html">Home</a> » <a href="#">Mi cuenta</a> » <a href="login.html">Login</a> </div>
        <!--Breadcrumb Part End-->
        <h1>Login CiudadVista</h1>
        <div class="login-content">
          <div class="left">
            <h2>Nuevo Usuario</h2>
            <div class="content">
              <p><b>Regístrese!</b></p>
              <p>Creando una cuenta podrá acceder a toda la información de planes, actividades y servicios en la ciudad, además de mantenerse en contacto con sus amigos y compartir con la comunidad los sitios que ha visitado y su opinión al respecto.</p>
              <a class="button" href="#">Continuar</a></br></br>
			   <p><b>¿Empresario, emprendedor?</b></p>
              <p>CiudadVista está abierta a la divulgación y promoción de empresas emergentes, esta es lo oportunidad que ha estado buscando</p>
              <a class="button" href="#">Ver más</a></br></br>
			  <p><b>Gestores culturales</b></p>
              <p>CiudadVista busca promover el desarrollo de actividades culturales en la ciudad, dando la oportunidad a promotores culturales de exponer sus propuestas e invitar la ciudadanía a participar.</p>
              <a class="button" href="#">Ver más</a>
			  </div>
          </div>
        <div class="right">
            <h2>Ingreso a la aplicación</h2>
				   <g:form class="simpleform" style="width:50%;" url="[controller:'Usuario',action:'loginT']">

				      <p class="info">
				        <g:link controller="user" action="register">Ingrese sus datos de ingreso!</g:link>
				      </p>
				      <g:if test="${flash.message}">
				          <div class="message">${flash.message}</div>
				      </g:if>
				      <p>
				        <label for="email">E-mail</label>
				        <g:textField name="email" />
				      </p>
				      <p>
				        <label for="password">Password</label>
				        <g:passwordField name="password" />
				      </p>
				      <p class="button">
				        <label>&nbsp;</label>
				        <g:submitButton class="button" name="submitButton" value="Login" />
				      </p>
				  </g:form>
                 </div>
            
        </div>
      </div>
      <!--Middle Part End-->
      <div class="clear"></div>
    </div>  
  <!--Footer Part End-->
  
  <g:render template="/common/footer" />
  
  
</div>
</body>
</html>

grails-app/views/usuario/show.gsp
<%@ page import="cvista_login.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-usuario" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-usuario" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list usuario">
			
				<g:if test="${usuarioInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="usuario.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${usuarioInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioInstance?.password}">
				<li class="fieldcontain">
					<span id="password-label" class="property-label"><g:message code="usuario.password.label" default="Password" /></span>
					
						<span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${usuarioInstance}" field="password"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioInstance?.activo}">
				<li class="fieldcontain">
					<span id="activo-label" class="property-label"><g:message code="usuario.activo.label" default="Activo" /></span>
					
						<span class="property-value" aria-labelledby="activo-label"><g:formatBoolean boolean="${usuarioInstance?.activo}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:usuarioInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${usuarioInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>