grails-app/domain/cvista_login/Servicio.groovy
package cvista_login

import java.util.Date;
import java.util.List;



class Servicio extends Componente{


	Date fechaActivo
	Date fechaInactivo
	

	
	static belogsTo = UsuarioEmpresario

	static constraints = {
		fechaActivo() 
		fechaInactivo()
		picture(nullable:true)
	}
	static mapping = { sort "fechaActivo":"desc" }
}

grails-app/controllers/cvista_login/ServicioController.groovy
package cvista_login



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ServicioController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Servicio.list(params), model:[servicioInstanceCount: Servicio.count()]
    }

    def show(Servicio servicioInstance) {
        respond servicioInstance
    }

    def create() {
        respond new Servicio(params)
    }

    @Transactional
    def save(Servicio servicioInstance) {
       if (servicioInstance == null) {
			notFound2()
			return
		}
		def file = request.getFile('picture')
		if(file.empty) {
			flash.message =  "no file"
			
		}
		else if(!file.getContentType().equals("image/jpeg")&&!file.getContentType().equals("image/png")&&!file.getContentType().equals("image/pjpeg"))
		{
			flash.message = "bad type"
		}
		else {
			
			servicioInstance.picture = file.getBytes()
			servicioInstance.pictureType = file.getContentType()
			servicioInstance.pictureName = file.originalFilename
			println file.getContentType()
			println file.originalFilename
			
		}
		
		def act = new Servicio()
		act.properties = servicioInstance.properties
		
		if (act.hasErrors()) {
			respond servicioInstance.errors, view:'create2'
			return
		}	
		act.save flush:true
    }

    def edit(Servicio servicioInstance) {
        respond servicioInstance
    }

    @Transactional
    def update(Servicio servicioInstance) {
        if (servicioInstance == null) {
            notFound()
            return
        }

        if (servicioInstance.hasErrors()) {
            respond servicioInstance.errors, view:'edit'
            return
        }

        servicioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Servicio.label', default: 'Servicio'), servicioInstance.id])
                redirect servicioInstance
            }
            '*'{ respond servicioInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Servicio servicioInstance) {

        if (servicioInstance == null) {
            notFound()
            return
        }

        servicioInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Servicio.label', default: 'Servicio'), servicioInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'servicio.label', default: 'Servicio'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
	
	
	def index2(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		respond Servicio.list(params), model:[servicioInstanceCount: Servicio.count()]
	}

	def show2(Servicio servicioInstance) {
		respond servicioInstance
	}

	def create2() {
		respond new Servicio(params)
	}

	@Transactional
	def save2(Servicio servicioInstance) {
		
		if (servicioInstance == null) {
			notFound2()
			return
		}
		def file = request.getFile('picture')
		if(file.empty) {
			flash.message =  "no file"
			
		}
		else if(!file.getContentType().equals("image/jpeg")&&!file.getContentType().equals("image/png")&&!file.getContentType().equals("image/pjpeg"))
		{
			flash.message = "bad type"
		}
		else {
			
			servicioInstance.picture = file.getBytes()
			servicioInstance.pictureType = file.getContentType()
			servicioInstance.pictureName = file.originalFilename
			println file.getContentType()
			println file.originalFilename
			
		}
		
		def act = new Servicio()
		act.properties = servicioInstance.properties
		
		if (act.hasErrors()) {
			respond servicioInstance.errors, view:'create2'
			return
		}	
		act.save flush:true
		
	/*
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [message(code: 'actividad.label', default: 'Actividad'), actividadInstance.id])
				redirect actividadInstance
			}
			'*' { respond actividadInstance, [status: CREATED] }
		}}*/
		redirect view: 'show2'
	}

	def edit2(Servicio servicioInstance) {
		respond servicioInstance
	}

	@Transactional
	def update2(Servicio servicioInstance) {
		if (servicioInstance == null) {
			notFound2()
			return
		}

		if (servicioInstance.hasErrors()) {
			respond servicioInstance.errors, view:'edit2'
			return
		}

		servicioInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'Servicio.label', default: 'Servicio'), servicioInstance.id])
				redirect servicioInstance
			}
			'*'{ respond servicioInstance, [status: OK] }
		}
	}

	@Transactional
	def delete2(Servicio servicioInstance) {

		if (servicioInstance == null) {
			notFound2()
			return
		}

		servicioInstance.delete flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.deleted.message', args: [message(code: 'Servicio.label', default: 'Servicio'), servicioInstance.id])
				redirect action:"index2", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}

	protected void notFound2() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [message(code: 'servicio.label', default: 'Servicio'), params.id])
				redirect action: "index2", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/servicio/_form.gsp
<%@ page import="cvista_login.Servicio" %>



<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'nombreComponente', 'error')} required">
	<label for="nombreComponente">
		<g:message code="servicio.nombreComponente.label" default="Nombre Componente" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombreComponente" required="" value="${servicioInstance?.nombreComponente}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'activo', 'error')} ">
	<label for="activo">
		<g:message code="servicio.activo.label" default="Activo" />
		
	</label>
	<g:checkBox name="activo" value="${servicioInstance?.activo}" />

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'resumen', 'error')} required">
	<label for="resumen">
		<g:message code="servicio.resumen.label" default="Resumen" />
		<span class="required-indicator">*</span>
	</label>
	<g:textArea name="resumen" cols="40" rows="5" maxlength="1000" required="" value="${servicioInstance?.resumen}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'ranking', 'error')} required">
	<label for="ranking">
		<g:message code="servicio.ranking.label" default="Ranking" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="ranking" type="number" value="${servicioInstance.ranking}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'fechaActivo', 'error')} required">
	<label for="fechaActivo">
		<g:message code="servicio.fechaActivo.label" default="Fecha Activo" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="fechaActivo" precision="day"  value="${servicioInstance?.fechaActivo}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'fechaInactivo', 'error')} required">
	<label for="fechaInactivo">
		<g:message code="servicio.fechaInactivo.label" default="Fecha Inactivo" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="fechaInactivo" precision="day"  value="${servicioInstance?.fechaInactivo}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'picture', 'error')} ">
	<label for="picture">
		<g:message code="servicio.picture.label" default="Picture" />
		
	</label>
	<input type="file" id="picture" name="picture"  value="${request.picture}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: servicioInstance, field: 'comentarios', 'error')} ">
	<label for="comentarios">
		<g:message code="servicio.comentarios.label" default="Comentarios" />
		
	</label>
	<g:select name="comentarios" from="${cvista_login.Comentario.list()}" multiple="multiple" optionKey="id" size="5" value="${servicioInstance?.comentarios*.id}" class="many-to-many"/>

</div>

grails-app/views/servicio/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'servicio.label', default: 'Servicio')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-servicio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-servicio" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${servicioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${servicioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:uploadForm url="[resource:servicioInstance, action:'save']"  enctype="multipart/form-data">
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:uploadForm>
		</div>
	</body>
</html>

grails-app/views/servicio/create2.gsp
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'servicio.label', default: 'Servicio')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#create-servicio" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="list" action="index2">
												<g:message code="default.list.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="create-servicio" class="content scaffold-create"
									role="main">
									<h1>
										<g:message code="default.create.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<g:hasErrors bean="${servicioInstance}">
										<ul class="errors" role="alert">
											<g:eachError bean="${servicioInstance}" var="error">
												<li
													<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
														error="${error}" /></li>
											</g:eachError>
										</ul>
									</g:hasErrors>
									<g:uploadForm url="[resource:servicioInstance, action:'save2']"
										enctype="multipart/form-data">
										<fieldset class="form">
											<g:render template="form" />
										</fieldset>
										<fieldset class="buttons">
											<g:submitButton name="create" class="save"
												value="${message(code: 'default.button.create.label', default: 'Create')}" />
										</fieldset>
									</g:uploadForm>
									
									
								</div>



							</div>
						</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>

grails-app/views/servicio/edit.gsp
<%@ page import="cvista_login.Servicio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'servicio.label', default: 'Servicio')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-servicio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-servicio" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${servicioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${servicioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:servicioInstance, action:'update']" method="PUT"  enctype="multipart/form-data">
				<g:hiddenField name="version" value="${servicioInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/servicio/edit2.gsp
<%@ page import="cvista_login.Servicio" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'servicio.label', default: 'Servicio')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#edit-servicio" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="list" action="index2">
												<g:message code="default.list.label" args="[entityName]" />
											</g:link></li>
										<li><g:link class="create" action="create2">
												<g:message code="default.new.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="edit-servicio" class="content scaffold-edit"
									role="main">
									<h1>
										<g:message code="default.edit.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<g:hasErrors bean="${servicioInstance}">
										<ul class="errors" role="alert">
											<g:eachError bean="${servicioInstance}" var="error">
												<li
													<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
														error="${error}" /></li>
											</g:eachError>
										</ul>
									</g:hasErrors>
									<g:form url="[resource:servicioInstance, action:'update2']"
										method="PUT" enctype="multipart/form-data">
										<g:hiddenField name="version"
											value="${servicioInstance?.version}" />
										<fieldset class="form">
											<g:render template="form" />
										</fieldset>
										<fieldset class="buttons">
											<g:actionSubmit class="save" action="update2"
												value="${message(code: 'default.button.update.label', default: 'Update')}" />
										</fieldset>
									</g:form>
								</div>



							</div>
						</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>

grails-app/views/servicio/index.gsp
<%@ page import="cvista_login.Servicio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'servicio.label', default: 'Servicio')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-servicio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-servicio" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nombreComponente" title="${message(code: 'servicio.nombreComponente.label', default: 'Nombre Componente')}" />
					
						<g:sortableColumn property="activo" title="${message(code: 'servicio.activo.label', default: 'Activo')}" />
					
						<g:sortableColumn property="resumen" title="${message(code: 'servicio.resumen.label', default: 'Resumen')}" />
					
						<g:sortableColumn property="ranking" title="${message(code: 'servicio.ranking.label', default: 'Ranking')}" />
					
						<g:sortableColumn property="fechaActivo" title="${message(code: 'servicio.fechaActivo.label', default: 'Fecha Activo')}" />
					
						<g:sortableColumn property="fechaInactivo" title="${message(code: 'servicio.fechaInactivo.label', default: 'Fecha Inactivo')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${servicioInstanceList}" status="i" var="servicioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${servicioInstance.id}">${fieldValue(bean: servicioInstance, field: "nombreComponente")}</g:link></td>
					
						<td><g:formatBoolean boolean="${servicioInstance.activo}" /></td>
					
						<td>${fieldValue(bean: servicioInstance, field: "resumen")}</td>
					
						<td>${fieldValue(bean: servicioInstance, field: "ranking")}</td>
					
						<td><g:formatDate date="${servicioInstance.fechaActivo}" /></td>
					
						<td><g:formatDate date="${servicioInstance.fechaInactivo}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${servicioInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/servicio/index2.gsp
<%@ page import="cvista_login.Servicio" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'servicio.label', default: 'Servicio')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#list-servicio" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="create" action="create2">
												<g:message code="default.new.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="list-servicio" class="content scaffold-list"
									role="main">
									<h1>
										<g:message code="default.list.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<table>
										<thead>
											<tr>

												<g:sortableColumn property="nombreComponente"
													title="${message(code: 'servicio.nombreComponente.label', default: 'Nombre Componente')}" />

												<g:sortableColumn property="activo"
													title="${message(code: 'servicio.activo.label', default: 'Activo')}" />

												<g:sortableColumn property="resumen"
													title="${message(code: 'servicio.resumen.label', default: 'Resumen')}" />

												<g:sortableColumn property="ranking"
													title="${message(code: 'servicio.ranking.label', default: 'Ranking')}" />

												<g:sortableColumn property="fechaActivo"
													title="${message(code: 'servicio.fechaActivo.label', default: 'Fecha Activo')}" />

												<g:sortableColumn property="fechaInactivo"
													title="${message(code: 'servicio.fechaInactivo.label', default: 'Fecha Inactivo')}" />

											</tr>
										</thead>
										<tbody>
											<g:each in="${servicioInstanceList}" status="i"
												var="servicioInstance">
												<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

													<td><g:link action="show2" id="${servicioInstance.id}">
															${fieldValue(bean: servicioInstance, field: "nombreComponente")}
														</g:link></td>

													<td><g:formatBoolean
															boolean="${servicioInstance.activo}" /></td>

													<td>
														${fieldValue(bean: servicioInstance, field: "resumen")}
													</td>

													<td>
														${fieldValue(bean: servicioInstance, field: "ranking")}
													</td>

													<td><g:formatDate
															date="${servicioInstance.fechaActivo}" /></td>

													<td><g:formatDate
															date="${servicioInstance.fechaInactivo}" /></td>

												</tr>
											</g:each>
										</tbody>
									</table>
									<div class="pagination">
										<g:paginate total="${servicioInstanceCount ?: 0}" />
									</div>
								</div>



							</div>
						</div>
					</div>
				</div>
				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>