grails-app/domain/cvista_login/UsuarioPromotor.groovy
package cvista_login


import java.util.List;

class UsuarioPromotor extends Usuario  {
	String nombreRazonCultural;
	String nombreApellido
	long cedula



	static hasMany=[actividades:Actividad]
	List actividades
	
	UsuarioPromotor(){
		this.actividades = new ArrayList()
	}

	static constraints = {
		nombreApellido()
		nombreRazonCultural()
		cedula(unique:true)
	
	}
}

grails-app/controllers/cvista_login/UsuarioPromotorController.groovy
package cvista_login
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UsuarioPromotorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond UsuarioPromotor.list(params), model:[usuarioPromotorInstanceCount: UsuarioPromotor.count()]
    }

    def show(UsuarioPromotor usuarioPromotorInstance) {
        respond usuarioPromotorInstance
    }

	
	
    def create() {
        respond new UsuarioPromotor(params)
    }
	
	def index2(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		respond UsuarioPromotor.list(params), model:[usuarioPromotorInstanceCount: UsuarioPromotor.count()]
	}

	def show2(UsuarioPromotor usuarioPromotorInstance) {
		respond usuarioPromotorInstance
	}

	def create2() {
		respond new UsuarioPromotor(params)
	}
	
    @Transactional
    def save(UsuarioPromotor usuarioPromotorInstance) {
       if (usuarioPromotorInstance == null) {
			notFound2()
			return
		}
		def file = request.getFile('picture')
		if(!file.getContentType().equals("image/jpeg")&&!file.getContentType().equals("image/png")&&!file.getContentType().equals("image/pjpeg"))
		{
			flash.message = "bad type"
		}
		else {
			
			usuarioPromotorInstance.picture = file.getBytes()
			usuarioPromotorInstance.pictureType = file.getContentType()
			usuarioPromotorInstance.pictureName = file.originalFilename			
		}

		
		def act = new UsuarioPromotor()
		act.properties = usuarioPromotorInstance.properties
		
		if (act.hasErrors()) {
			respond usuarioPromotorInstance.errors, view:'create2'
			return
		}	
		act.save flush:true
    }

    def edit(UsuarioPromotor usuarioPromotorInstance) {
        respond usuarioPromotorInstance
    }

    @Transactional
    def update(UsuarioPromotor usuarioPromotorInstance) {
        if (usuarioPromotorInstance == null) {
            notFound()
            return
        }

        if (usuarioPromotorInstance.hasErrors()) {
            respond usuarioPromotorInstance.errors, view:'edit'
            return
        }

        usuarioPromotorInstance.save flush:true
		usuarioPromotorInstance.password = usuarioPromotorInstance.password.encodeAsMD5()
		
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'UsuarioPromotor.label', default: 'UsuarioPromotor'), usuarioPromotorInstance.id])
                redirect usuarioPromotorInstance
            }
            '*'{ respond usuarioPromotorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(UsuarioPromotor usuarioPromotorInstance) {

        if (usuarioPromotorInstance == null) {
            notFound()
            return
        }

        usuarioPromotorInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'UsuarioPromotor.label', default: 'UsuarioPromotor'), usuarioPromotorInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuarioPromotor.label', default: 'UsuarioPromotor'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
	
	
	@Transactional
	def save2(UsuarioPromotor usuarioPromotorInstance) {
		
		if (usuarioPromotorInstance == null) {
			notFound2()
			return
		}
		def file = request.getFile('picture')
		if(!file.getContentType().equals("image/jpeg")&&!file.getContentType().equals("image/png")&&!file.getContentType().equals("image/pjpeg"))
		{
			flash.message = "bad type"
		}
		else {
			
			usuarioPromotorInstance.picture = file.getBytes()
			usuarioPromotorInstance.pictureType = file.getContentType()
			usuarioPromotorInstance.pictureName = file.originalFilename			
		}

		
		def act = new UsuarioPromotor()
		act.properties = usuarioPromotorInstance.properties
		
		if (act.hasErrors()) {
			respond usuarioPromotorInstance.errors, view:'create2'
			return
		}	
		act.save flush:true
		
	/*
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [message(code: 'actividad.label', default: 'Actividad'), actividadInstance.id])
				redirect actividadInstance
			}
			'*' { respond actividadInstance, [status: CREATED] }
		}}*/
		redirect view: 'show2'
	}

	def edit2(UsuarioPromotor usuarioPromotorInstance) {
		respond usuarioPromotorInstance
	}

	@Transactional
	def update2(UsuarioPromotor usuarioPromotorInstance) {
		if (usuarioPromotorInstance == null) {
			notFound2()
			return
		}

		if (usuarioPromotorInstance.hasErrors()) {
			respond usuarioPromotorInstance.errors, view:'edit2'
			return
		}

		usuarioPromotorInstance.save flush:true
		usuarioPromotorInstance.password = usuarioPromotorInstance.password.encodeAsMD5()
		
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'UsuarioPromotor.label', default: 'UsuarioPromotor'), usuarioPromotorInstance.id])
				redirect usuarioPromotorInstance
			}
			'*'{ respond usuarioPromotorInstance, [status: OK] }
		}
	}

	@Transactional
	def delete2(UsuarioPromotor usuarioPromotorInstance) {

		if (usuarioPromotorInstance == null) {
			notFound2()
			return
		}

		usuarioPromotorInstance.delete flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.deleted.message', args: [message(code: 'UsuarioPromotor.label', default: 'UsuarioPromotor'), usuarioPromotorInstance.id])
				redirect action:"index2", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}
	
	
	protected void notFound2() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [message(code: 'usuarioPromotor.label', default: 'UsuarioPromotor'), params.id])
				redirect action: "index2", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/usuarioPromotor/Show2.gsp
<%@ page import="cvista_login.UsuarioPromotor" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'usuarioEmpresario.label', default: 'UsuarioEmpresario')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#show-usuarioPromotor" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/'panel)}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="list" action="index2">
												<g:message code="default.list.label" args="[entityName]" />
											</g:link></li>
										<li><g:link class="create" action="create2">
												<g:message code="default.new.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="show-usuarioPromotor" class="content scaffold-show"
									role="main">
									<h1>
										<g:message code="default.show.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<ol class="property-list usuarioPromotor">

										<g:if test="${usuarioPromotorInstance?.email}">
											<li class="fieldcontain"><span id="email-label"
												class="property-label"><g:message
														code="usuarioPromotor.email.label" default="Email" /></span> <span
												class="property-value" aria-labelledby="email-label"><g:fieldValue
														bean="${usuarioPromotorInstance}" field="email" /></span></li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.password}">
											<li class="fieldcontain"><span id="password-label"
												class="property-label"><g:message
														code="usuarioPromotor.password.label" default="Password" /></span>

												<span class="property-value"
												aria-labelledby="password-label"><g:fieldValue
														bean="${usuarioPromotorInstance}" field="password" /></span></li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.activo}">
											<li class="fieldcontain"><span id="activo-label"
												class="property-label"><g:message
														code="usuarioPromotor.activo.label" default="Activo" /></span> <span
												class="property-value" aria-labelledby="activo-label"><g:formatBoolean
														boolean="${usuarioPromotorInstance?.activo}" /></span></li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.nombreApellido}">
											<li class="fieldcontain"><span id="nombreApellido-label"
												class="property-label"><g:message
														code="usuarioPromotor.nombreApellido.label"
														default="Nombre Apellido" /></span> <span class="property-value"
												aria-labelledby="nombreApellido-label"><g:fieldValue
														bean="${usuarioPromotorInstance}" field="nombreApellido" /></span>

											</li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.nombreRazonCultural}">
											<li class="fieldcontain"><span
												id="nombreRazonCultural-label" class="property-label"><g:message
														code="usuarioPromotor.nombreRazonCultural.label"
														default="Nombre Razon Cultural" /></span> <span
												class="property-value"
												aria-labelledby="nombreRazonCultural-label"><g:fieldValue
														bean="${usuarioPromotorInstance}"
														field="nombreRazonCultural" /></span></li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.cedula}">
											<li class="fieldcontain"><span id="cedula-label"
												class="property-label"><g:message
														code="usuarioPromotor.cedula.label" default="Cedula" /></span> <span
												class="property-value" aria-labelledby="cedula-label"><g:fieldValue
														bean="${usuarioPromotorInstance}" field="cedula" /></span></li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.picture}">
											<li class="fieldcontain"><span id="picture-label"
												class="property-label"><g:message
														code="usuarioPromotor.picture.label" default="Picture" /></span>

											</li>
										</g:if>

										<g:if test="${usuarioPromotorInstance?.actividades}">
											<li class="fieldcontain"><span id="actividades-label"
												class="property-label"><g:message
														code="usuarioPromotor.actividades.label"
														default="Actividades" /></span> <g:each
													in="${usuarioPromotorInstance.actividades}" var="a">
													<span class="property-value"
														aria-labelledby="actividades-label"><g:link
															controller="actividad" action="show" id="${a.id}">
															${a?.encodeAsHTML()}
														</g:link></span>
												</g:each></li>
										</g:if>

									</ol>
									<g:form
										url="[resource:usuarioPromotorInstance, action:'delete2']"
										method="DELETE">
										<fieldset class="buttons">
											<g:link class="edit" action="edit2"
												resource="${usuarioPromotorInstance}">
												<g:message code="default.button.edit.label" default="Edit" />
											</g:link>
											<g:actionSubmit class="delete" action="delete2"
												value="${message(code: 'default.button.delete.label', default: 'Delete')}"
												onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
										</fieldset>
									</g:form>


								</div>
							</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>

grails-app/views/usuarioPromotor/_form.gsp
<%@ page import="cvista_login.UsuarioPromotor" %>



<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="usuarioPromotor.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="email" required="" value="${usuarioPromotorInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="usuarioPromotor.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="password" name="password" required="" value="${usuarioPromotorInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'activo', 'error')} ">
	<label for="activo">
		<g:message code="usuarioPromotor.activo.label" default="Activo" />
		
	</label>
	<g:checkBox name="activo" value="${usuarioPromotorInstance?.activo}" />

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'nombreApellido', 'error')} required">
	<label for="nombreApellido">
		<g:message code="usuarioPromotor.nombreApellido.label" default="Nombre Apellido" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombreApellido" required="" value="${usuarioPromotorInstance?.nombreApellido}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'nombreRazonCultural', 'error')} required">
	<label for="nombreRazonCultural">
		<g:message code="usuarioPromotor.nombreRazonCultural.label" default="Nombre Razon Cultural" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombreRazonCultural" required="" value="${usuarioPromotorInstance?.nombreRazonCultural}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'cedula', 'error')} required">
	<label for="cedula">
		<g:message code="usuarioPromotor.cedula.label" default="Cedula" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="cedula" type="number" value="${usuarioPromotorInstance.cedula}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'picture', 'error')} ">
	<label for="picture">
		<g:message code="usuarioPromotor.picture.label" default="Picture" />
		
	</label>
	<input type="file" id="picture" name="picture"  value="${request.picture}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: usuarioPromotorInstance, field: 'actividades', 'error')} ">
	<label for="actividades">
		<g:message code="usuarioPromotor.actividades.label" default="Actividades" />
		
	</label>
	<g:select name="actividades" from="${cvista_login.Actividad.list()}" multiple="multiple" optionKey="id" size="5" value="${usuarioPromotorInstance?.actividades*.id}" class="many-to-many"/>

</div>

grails-app/views/usuarioPromotor/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuarioPromotor.label', default: 'UsuarioPromotor')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-usuarioPromotor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-usuarioPromotor" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioPromotorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${usuarioPromotorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:uploadForm url="[resource:usuarioPromotorInstance, action:'save']"  enctype="multipart/form-data">
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:uploadForm>
		</div>
	</body>
</html>

grails-app/views/usuarioPromotor/index.gsp
<%@ page import="cvista_login.UsuarioPromotor" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuarioPromotor.label', default: 'UsuarioPromotor')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-usuarioPromotor" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-usuarioPromotor" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="email" title="${message(code: 'usuarioPromotor.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'usuarioPromotor.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="activo" title="${message(code: 'usuarioPromotor.activo.label', default: 'Activo')}" />
					
						<g:sortableColumn property="nombreApellido" title="${message(code: 'usuarioPromotor.nombreApellido.label', default: 'Nombre Apellido')}" />
					
						<g:sortableColumn property="nombreRazonCultural" title="${message(code: 'usuarioPromotor.nombreRazonCultural.label', default: 'Nombre Razon Cultural')}" />
					
						<g:sortableColumn property="cedula" title="${message(code: 'usuarioPromotor.cedula.label', default: 'Cedula')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioPromotorInstanceList}" status="i" var="usuarioPromotorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${usuarioPromotorInstance.id}">${fieldValue(bean: usuarioPromotorInstance, field: "email")}</g:link></td>
					
						<td>${fieldValue(bean: usuarioPromotorInstance, field: "password")}</td>
					
						<td><g:formatBoolean boolean="${usuarioPromotorInstance.activo}" /></td>
					
						<td>${fieldValue(bean: usuarioPromotorInstance, field: "nombreApellido")}</td>
					
						<td>${fieldValue(bean: usuarioPromotorInstance, field: "nombreRazonCultural")}</td>
					
						<td>${fieldValue(bean: usuarioPromotorInstance, field: "cedula")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${usuarioPromotorInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/usuarioPromotor/index2.gsp
<%@ page import="cvista_login.UsuarioPromotor" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'usuarioEmpresario.label', default: 'UsuarioEmpresario')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#list-usuarioPromotor" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="create" action="create2">
												<g:message code="default.new.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="list-usuarioPromotor" class="content scaffold-list"
									role="main">
									<h1>
										<g:message code="default.list.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<table>
										<thead>
											<tr>

												<g:sortableColumn property="email"
													title="${message(code: 'usuarioPromotor.email.label', default: 'Email')}" />

												<g:sortableColumn property="password"
													title="${message(code: 'usuarioPromotor.password.label', default: 'Password')}" />

												<g:sortableColumn property="activo"
													title="${message(code: 'usuarioPromotor.activo.label', default: 'Activo')}" />

												<g:sortableColumn property="nombreApellido"
													title="${message(code: 'usuarioPromotor.nombreApellido.label', default: 'Nombre Apellido')}" />

												<g:sortableColumn property="nombreRazonCultural"
													title="${message(code: 'usuarioPromotor.nombreRazonCultural.label', default: 'Nombre Razon Cultural')}" />

												<g:sortableColumn property="cedula"
													title="${message(code: 'usuarioPromotor.cedula.label', default: 'Cedula')}" />

											</tr>
										</thead>
										<tbody>
											<g:each in="${usuarioPromotorInstanceList}" status="i"
												var="usuarioPromotorInstance">
												<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

													<td><g:link action="show2"
															id="${usuarioPromotorInstance.id}">
															${fieldValue(bean: usuarioPromotorInstance, field: "email")}
														</g:link></td>

													<td>
														${fieldValue(bean: usuarioPromotorInstance, field: "password")}
													</td>

													<td><g:formatBoolean
															boolean="${usuarioPromotorInstance.activo}" /></td>

													<td>
														${fieldValue(bean: usuarioPromotorInstance, field: "nombreApellido")}
													</td>

													<td>
														${fieldValue(bean: usuarioPromotorInstance, field: "nombreRazonCultural")}
													</td>

													<td>
														${fieldValue(bean: usuarioPromotorInstance, field: "cedula")}
													</td>

												</tr>
											</g:each>
										</tbody>
									</table>
									<div class="pagination">
										<g:paginate total="${usuarioPromotorInstanceCount ?: 0}" />
									</div>
								</div>



							</div>
						</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>