grails-app/domain/cvista_login/Sitio.groovy
package cvista_login
import java.util.List;



class Sitio extends Componente{
	
	boolean esPublico
	String direccion
	String telefono
	Byte [] picture
	String lat
	String lng
	
	
	static hasMany=[actividades:Actividad,servicios:Servicio]
	List actividades
	List servicios
	
	Sitio(){
		this.actividades = new ArrayList()
		this.servicios = new ArrayList()
	}

    static constraints = {
		telefono()
		direccion()
		esPublico()
		picture(nullable:true)
		lat()
		lng()
    }
}

grails-app/controllers/cvista_login/SitioController.groovy
package cvista_login



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SitioController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Sitio.list(params), model:[sitioInstanceCount: Sitio.count()]
    }

    def show(Sitio sitioInstance) {
        respond sitioInstance
    }

    def create() {
        respond new Sitio(params)
    }

    @Transactional
    def save(Sitio sitioInstance) {
        if (sitioInstance == null) {
            notFound()
            return
        }

        if (sitioInstance.hasErrors()) {
            respond sitioInstance.errors, view:'create'
            return
        }

        sitioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'sitio.label', default: 'Sitio'), sitioInstance.id])
                redirect sitioInstance
            }
            '*' { respond sitioInstance, [status: CREATED] }
        }
    }

    def edit(Sitio sitioInstance) {
        respond sitioInstance
    }

    @Transactional
    def update(Sitio sitioInstance) {
        if (sitioInstance == null) {
            notFound()
            return
        }

        if (sitioInstance.hasErrors()) {
            respond sitioInstance.errors, view:'edit'
            return
        }

        sitioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Sitio.label', default: 'Sitio'), sitioInstance.id])
                redirect sitioInstance
            }
            '*'{ respond sitioInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Sitio sitioInstance) {

        if (sitioInstance == null) {
            notFound()
            return
        }

        sitioInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Sitio.label', default: 'Sitio'), sitioInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'sitio.label', default: 'Sitio'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
	
	
	def index2(Integer max) {
		params.max = Math.min(max ?: 10, 100)
		respond Sitio.list(params), model:[sitioInstanceCount: Sitio.count()]
	}

	def show2(Sitio sitioInstance) {
		respond sitioInstance
	}

	def create2() {
		respond new Sitio(params)
	}

	@Transactional
	def save2(Sitio sitioInstance) {
		if (sitioInstance == null) {
			notFound2()
			return
		}

		if (sitioInstance.hasErrors()) {
			respond sitioInstance.errors, view:'create2'
			return
		}

		sitioInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.created.message', args: [message(code: 'sitio.label', default: 'Sitio'), sitioInstance.id])
				redirect sitioInstance
			}
			'*' { respond sitioInstance, [status: CREATED] }
		}
	}
	
	
	
	def edit2(Sitio sitioInstance) {
		respond sitioInstance
	}

	@Transactional
	def update2(Sitio sitioInstance) {
		if (sitioInstance == null) {
			notFound2()
			return
		}

		if (sitioInstance.hasErrors()) {
			respond sitioInstance.errors, view:'edit2'
			return
		}

		sitioInstance.save flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.updated.message', args: [message(code: 'Sitio.label', default: 'Sitio'), sitioInstance.id])
				redirect sitioInstance
			}
			'*'{ respond sitioInstance, [status: OK] }
		}
	}

	@Transactional
	def delete2(Sitio sitioInstance) {

		if (sitioInstance == null) {
			notFound2()
			return
		}

		sitioInstance.delete flush:true

		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.deleted.message', args: [message(code: 'Sitio.label', default: 'Sitio'), sitioInstance.id])
				redirect action:"index2", method:"GET"
			}
			'*'{ render status: NO_CONTENT }
		}
	}

	protected void notFound2() {
		request.withFormat {
			form multipartForm {
				flash.message = message(code: 'default.not.found.message', args: [message(code: 'sitio.label', default: 'Sitio'), params.id])
				redirect action:"index2", method: "GET"
			}
			'*'{ render status: NOT_FOUND }
		}
	}
}

grails-app/views/sitio/_form.gsp
<%@ page import="cvista_login.Sitio" %>



<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'nombreComponente', 'error')} required">
	<label for="nombreComponente">
		<g:message code="sitio.nombreComponente.label" default="Nombre Componente" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nombreComponente" required="" value="${sitioInstance?.nombreComponente}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'activo', 'error')} ">
	<label for="activo">
		<g:message code="sitio.activo.label" default="Activo" />
		
	</label>
	<g:checkBox name="activo" value="${sitioInstance?.activo}" />

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'resumen', 'error')} required">
	<label for="resumen">
		<g:message code="sitio.resumen.label" default="Resumen" />
		<span class="required-indicator">*</span>
	</label>
	<g:textArea name="resumen" cols="40" rows="5" maxlength="1000" required="" value="${sitioInstance?.resumen}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'ranking', 'error')} required">
	<label for="ranking">
		<g:message code="sitio.ranking.label" default="Ranking" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="ranking" type="number" value="${sitioInstance.ranking}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'telefono', 'error')} required">
	<label for="telefono">
		<g:message code="sitio.telefono.label" default="Telefono" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="telefono" required="" value="${sitioInstance?.telefono}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'direccion', 'error')} required">
	<label for="direccion">
		<g:message code="sitio.direccion.label" default="Direccion" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="direccion" required="" value="${sitioInstance?.direccion}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'esPublico', 'error')} ">
	<label for="esPublico">
		<g:message code="sitio.esPublico.label" default="Es Publico" />
		
	</label>
	<g:checkBox name="esPublico" value="${sitioInstance?.esPublico}" />

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'picture', 'error')} ">
	<label for="picture">
		<g:message code="sitio.picture.label" default="Picture" />
		
	</label>
	<input type="file" id="picture" name="picture" />

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'lat', 'error')} required">
	<label for="lat">
		<g:message code="sitio.lat.label" default="Lat" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lat" required="" value="${sitioInstance?.lat}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'lng', 'error')} required">
	<label for="lng">
		<g:message code="sitio.lng.label" default="Lng" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lng" required="" value="${sitioInstance?.lng}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'actividades', 'error')} ">
	<label for="actividades">
		<g:message code="sitio.actividades.label" default="Actividades" />
		
	</label>
	<g:select name="actividades" from="${cvista_login.Actividad.list()}" multiple="multiple" optionKey="id" size="5" value="${sitioInstance?.actividades*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'comentarios', 'error')} ">
	<label for="comentarios">
		<g:message code="sitio.comentarios.label" default="Comentarios" />
		
	</label>
	<g:select name="comentarios" from="${cvista_login.Comentario.list()}" multiple="multiple" optionKey="id" size="5" value="${sitioInstance?.comentarios*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: sitioInstance, field: 'servicios', 'error')} ">
	<label for="servicios">
		<g:message code="sitio.servicios.label" default="Servicios" />
		
	</label>
	<g:select name="servicios" from="${cvista_login.Servicio.list()}" multiple="multiple" optionKey="id" size="5" value="${sitioInstance?.servicios*.id}" class="many-to-many"/>

</div>

grails-app/views/sitio/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sitio.label', default: 'Sitio')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-sitio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-sitio" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sitioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sitioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sitioInstance, action:'save']"  enctype="multipart/form-data">
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/sitio/create2.gsp
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'sitio.label', default: 'Sitio')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#create-sitio" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="list" action="index2">
												<g:message code="default.list.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="create-sitio" class="content scaffold-create"
									role="main">
									<h1>
										<g:message code="default.create.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<g:hasErrors bean="${sitioInstance}">
										<ul class="errors" role="alert">
											<g:eachError bean="${sitioInstance}" var="error">
												<li
													<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
														error="${error}" /></li>
											</g:eachError>
										</ul>
									</g:hasErrors>
									<g:form url="[resource:sitioInstance, action:'save2']"
										enctype="multipart/form-data">
										<fieldset class="form">
											<g:render template="form" />
										</fieldset>
										<fieldset class="buttons">
											<g:submitButton name="create" class="save"
												value="${message(code: 'default.button.create.label', default: 'Create')}" />
										</fieldset>
									</g:form>
								</div>



							</div>
						</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>

grails-app/views/sitio/edit.gsp
<%@ page import="cvista_login.Sitio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sitio.label', default: 'Sitio')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-sitio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-sitio" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${sitioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${sitioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:sitioInstance, action:'update']" method="PUT"  enctype="multipart/form-data">
				<g:hiddenField name="version" value="${sitioInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/sitio/edit2.gsp
<%@ page import="cvista_login.Sitio" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'sitio.label', default: 'Sitio')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#edit-sitio" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="list" action="index2">
												<g:message code="default.list.label" args="[entityName]" />
											</g:link></li>
										<li><g:link class="create" action="create2">
												<g:message code="default.new.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="edit-sitio" class="content scaffold-edit" role="main">
									<h1>
										<g:message code="default.edit.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<g:hasErrors bean="${sitioInstance}">
										<ul class="errors" role="alert">
											<g:eachError bean="${sitioInstance}" var="error">
												<li
													<g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
														error="${error}" /></li>
											</g:eachError>
										</ul>
									</g:hasErrors>
									<g:form url="[resource:sitioInstance, action:'update2']"
										method="PUT" enctype="multipart/form-data">
										<g:hiddenField name="version"
											value="${sitioInstance?.version}" />
										<fieldset class="form">
											<g:render template="form" />
										</fieldset>
										<fieldset class="buttons">
											<g:actionSubmit class="save" action="update2"
												value="${message(code: 'default.button.update.label', default: 'Update')}" />
										</fieldset>
									</g:form>
								</div>



							</div>
						</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>

grails-app/views/sitio/index.gsp
<%@ page import="cvista_login.Sitio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'sitio.label', default: 'Sitio')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-sitio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-sitio" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nombreComponente" title="${message(code: 'sitio.nombreComponente.label', default: 'Nombre Componente')}" />
					
						<g:sortableColumn property="activo" title="${message(code: 'sitio.activo.label', default: 'Activo')}" />
					
						<g:sortableColumn property="resumen" title="${message(code: 'sitio.resumen.label', default: 'Resumen')}" />
					
						<g:sortableColumn property="ranking" title="${message(code: 'sitio.ranking.label', default: 'Ranking')}" />
					
						<g:sortableColumn property="telefono" title="${message(code: 'sitio.telefono.label', default: 'Telefono')}" />
					
						<g:sortableColumn property="direccion" title="${message(code: 'sitio.direccion.label', default: 'Direccion')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${sitioInstanceList}" status="i" var="sitioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${sitioInstance.id}">${fieldValue(bean: sitioInstance, field: "nombreComponente")}</g:link></td>
					
						<td><g:formatBoolean boolean="${sitioInstance.activo}" /></td>
					
						<td>${fieldValue(bean: sitioInstance, field: "resumen")}</td>
					
						<td>${fieldValue(bean: sitioInstance, field: "ranking")}</td>
					
						<td>${fieldValue(bean: sitioInstance, field: "telefono")}</td>
					
						<td>${fieldValue(bean: sitioInstance, field: "direccion")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${sitioInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/sitio/index2.gsp
<%@ page import="cvista_login.Sitio" %>


<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8" />
<g:set var="entityName" value="${message(code: 'sitio.label', default: 'Sitio')}" />
<title><g:message code="default.create.label" args="[entityName]" /></title>
<asset:stylesheet src="bootstrap.css" />
<asset:stylesheet src="font-awesome.css" />
<asset:stylesheet src="morris-0.4.3.min.css" />
<asset:stylesheet src="custom2.css" />
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<div id="wrapper">
		<%-- Render de la barra superior--%>
		<g:render template="/common/topPanel" />
		<%-- Render de la barra lateral, menu de opciones--%>
		<g:render template="/common/leftSide" />

		<!-- /. NAV SIDE  -->
		<div id="page-wrapper">
			<div id="page-inner">
				<div class="row">
				</div>
				<!-- /. ROW  -->
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<a href="#list-sitio" class="skip" tabindex="-1"><g:message
										code="default.link.skip.label"
										default="Skip to content&hellip;" /></a>
								<div class="nav1" role="navigation">
									<ul>
										<li><a class="home" href="${createLink(uri: '/panel')}"><g:message
													code="default.home.label" /></a></li>
										<li><g:link class="create" action="create2">
												<g:message code="default.new.label" args="[entityName]" />
											</g:link></li>
									</ul>
								</div>
								<div id="list-sitio" class="content scaffold-list" role="main">
									<h1>
										<g:message code="default.list.label" args="[entityName]" />
									</h1>
									<g:if test="${flash.message}">
										<div class="message" role="status">
											${flash.message}
										</div>
									</g:if>
									<table>
										<thead>
											<tr>

												<g:sortableColumn property="nombreComponente"
													title="${message(code: 'sitio.nombreComponente.label', default: 'Nombre Componente')}" />

												<g:sortableColumn property="activo"
													title="${message(code: 'sitio.activo.label', default: 'Activo')}" />

												<g:sortableColumn property="resumen"
													title="${message(code: 'sitio.resumen.label', default: 'Resumen')}" />

												<g:sortableColumn property="ranking"
													title="${message(code: 'sitio.ranking.label', default: 'Ranking')}" />

												<g:sortableColumn property="telefono"
													title="${message(code: 'sitio.telefono.label', default: 'Telefono')}" />

												<g:sortableColumn property="direccion"
													title="${message(code: 'sitio.direccion.label', default: 'Direccion')}" />

											</tr>
										</thead>
										<tbody>
											<g:each in="${sitioInstanceList}" status="i"
												var="sitioInstance">
												<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

													<td><g:link action="show2" id="${sitioInstance.id}">
															${fieldValue(bean: sitioInstance, field: "nombreComponente")}
														</g:link></td>

													<td><g:formatBoolean boolean="${sitioInstance.activo}" /></td>

													<td>
														${fieldValue(bean: sitioInstance, field: "resumen")}
													</td>

													<td>
														${fieldValue(bean: sitioInstance, field: "ranking")}
													</td>

													<td>
														${fieldValue(bean: sitioInstance, field: "telefono")}
													</td>

													<td>
														${fieldValue(bean: sitioInstance, field: "direccion")}
													</td>

												</tr>
											</g:each>
										</tbody>
									</table>
									<div class="pagination">
										<g:paginate total="${sitioInstanceCount ?: 0}" />
									</div>
								</div>


							</div>
						</div>
					</div>
				</div>

				<!-- /. ROW  -->
			</div>
			<!-- /. PAGE INNER  -->
		</div>
		<!-- /. PAGE WRAPPER  -->
	</div>
	<!-- /. WRAPPER  -->
	<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
	<asset:javascript src="jquery-1.10.2.js" />
	<asset:javascript src="bootstrap.min.js" />
	<asset:javascript src="jquery.metisMenu.js" />
	<asset:javascript src="raphael-2.1.0.min.js" />
	<asset:javascript src="morris.js" />
	<asset:javascript src="custom2.js" />
</body>
</html>